contact/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import ContactFormView

app_name = "contact"
urlpatterns = [
    path("", ContactFormView.as_view(), name="index"),
    path(
        "success",
        TemplateView.as_view(template_name="contact/success.html"),
        name="success",
    ),
]

portal/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.http import HttpResponse
from django.conf.urls.i18n import i18n_patterns
from axes.admin import AccessLogAdmin
from invitations.views import AcceptInvite

from .admin import Admin2FASite

admin.site.__class__ = Admin2FASite
admin.site.site_header = (
    "COVID Health Portal administration | Administration du Portail Alerte COVID"
)
admin.site.site_title = admin.site.site_header


def disable_delete_permissions(cls, request, obj=None):
    return False


AccessLogAdmin.has_delete_permission = disable_delete_permissions

urlpatterns = [
    re_path(
        r"^robots.txt",
        lambda x: HttpResponse("User-Agent: *\nDisallow: /", content_type="text/plain"),
        name="robots_file",
    ),
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
]

invitation_patterns = (
    [
        # https://github.com/bee-keeper/django-invitations/blob/master/invitations/urls.py
        re_path(
            r"^accept-invite/(?P<key>\w+)/?$",
            AcceptInvite.as_view(),
            name="accept-invite",
        ),
    ],
    "invitations",
)

urlpatterns += i18n_patterns(
    path("", include("profiles.urls")),
    path("", include("covid_key.urls")),
    path("contact/", include("contact.urls")),
    path("invitations/", include(invitation_patterns, namespace="invitations"),),
)

portal/forms.py
from django import forms


class HealthcareBaseForm(forms.Form):
    def __init__(self, *args, **kwargs):
        # Remove the colon after field labels
        kwargs.setdefault("label_suffix", "")
        super().__init__(*args, **kwargs)

        # override field attributes: https://stackoverflow.com/a/56870308
        for field in self.fields:
            self.fields[field].widget.attrs.pop("autofocus", None)
            # remove autocomplete attributes
            self.fields[field].widget.attrs.update({"autocomplete": "off"})

portal/templates/includes/FIP_header.html
{% load static %}
{% load i18n %}
<div class="canada-flag">
    {% get_current_language as LANGUAGE_CODE %}
    {% if LANGUAGE_CODE == 'en' %}
        <img src="{% static 'img/sig-blk-en.svg' %}" alt="{% trans 'Government of Canada' %}" />
    {% else %}
        <img src="{% static 'img/sig-blk-fr.svg' %}" alt="{% trans 'Government of Canada' %}" />
    {% endif %}
</div>

portal/templates/includes/cds_form.html
{% load i18n %}

<form method="post" id="form--{{ request.resolver_match.url_name }}">
  {% csrf_token %}

  {# Include the hidden fields #}
  {% for hidden in form.hidden_fields %}
    {{ hidden }}
  {% endfor %}

  <div class="fieldWrapper--container{% if form.non_field_errors %} fieldWrapper--container--has-error{% endif %}">
    {# Include the visible fields #}
    {% for field in form.visible_fields %}
      <div class="fieldWrapper{% if field.errors %} fieldWrapper--has-error{% endif %}">
          {{ field.label_tag }}
          {% if field.errors %}
            <div class="error--{{ field.html_name }}">{{ field.errors|first }}</div>
          {% endif %}
          {% if field.help_text %}
            <div class="help--{{ field.html_name }}">{{ field.help_text }}</div>
          {% endif %}
          {{ field }}
      </div>
    {% endfor %}
  </div>

  <button type="submit">
    {% if submit_text %}
      {{ submit_text }}
    {% else %}
      {% trans "Submit" %}
    {% endif %}
  </button>
</form>

portal/templates/includes/error_list.html
{% load i18n %}

{% if form.errors %}
  <div class="errorlist--container" role="alert">
    <h2 class="errorlist--heading">
      {% trans "Please correct the errors on the page" %}
    </h2>
    <ol class="errorlist">
      {% for key,value in form.errors.items %}
        <li>
        {% if key == '__all__' %}
          <a href="#form--{{ request.resolver_match.url_name }}">
        {% else %}
          <a href="#id_{{ key }}">
        {% endif %}
          {{ value|first }}
          </a>
        </li>
      {% endfor %}
    </ol>
  </div>
{% endif %}

portal/templates/includes/expires_string.html
{% load i18n %}
{% load static %}
{% load tz %}
{% get_current_language as LANGUAGE_CODE %}

{% timezone "Canada/Eastern" %}
  <span>{% trans "Key expires" %}
    <time id="expiry-datetime" datetime="{{ expiry|date:'c' }}">
      {% if LANGUAGE_CODE == 'en' %}
          {{ expiry|date:"F j" }}
      {% else %}
          {{ expiry|date:"j F" }}
      {% endif %}

      {% trans "at" %}

      {% if LANGUAGE_CODE == 'en' %}
          {{ expiry|date:"f a e" }}
      {% else %}
          {{ expiry|date:"G \h i e" }}
      {% endif %}
    </time>
  </span>
{% endtimezone %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/locale/{{ LANGUAGE_CODE }}-ca.min.js"></script>
{{ LANGUAGE_CODE|json_script:"lang_code" }}
<script src="{% static 'js/time_formatting.js' %}"></script>

portal/templates/includes/footer.html
{% load static %}
{% load i18n %}

<footer>
    <div class="page--container">
        <div class="footer-links">
            <ul>
                <li><a href="{% url 'contact:index' %}">{% trans "Contact us" %}</a></li>
                <li><a href="{% url 'privacy' %}">{% trans "Privacy" %}</a></li>
            </ul>
        </div>
        <div class="canada-wordmark"><img src="{% static 'img/wmms-blk.svg' %}" alt="{% trans 'Symbol of the Government of Canada' %}" /></div>
    </div>
</footer>

portal/templates/includes/nav_header.html
{% load i18n %}
{% load language_switcher %}
<nav class="nav--header" aria-label="{% trans 'Language and account navigation' %}">
  <ul>
    <li>
      {% get_current_language as LANGUAGE_CODE %}
      {% get_language_info for "en" as langEn %}
      {% get_language_info for "fr" as langFr %}

      <h2 class="visually-hidden">{% trans "Language selection" }</h2>
      <a href="{% get_href LANGUAGE_CODE %}">{% get_lang_title LANGUAGE_CODE langEn langFr %}</a>

    </li>
    {% if user.is_authenticated %}
      <li><a href="{% url 'user_profile' user.id %}">{{ user.email }}</a></li>
      <li><a href="{% url 'logout' %}">{% trans 'Log out' %}</a></li>
    {% else %}
      <li><a href="{% url 'login' %}">{% trans 'Log in' %}</a></li>
    {% endif %}
  </ul>
</nav>

portal/templates/includes/nav_main.html
{% load i18n %}

<nav class="nav--main"  aria-label="{% trans 'Product navigation' %}">
  <div class="page--container">
    <ul>
      <li><a {% if request.resolver_match.url_name == 'start' %}class="active"{% endif %} href="{% url 'start' %}">{% trans "Start" %}</a></li>
      {% if user.is_admin %}
        <li><a {% if request.resolver_match.url_name == 'profiles' %}class="active"{% endif %} href="{% url 'profiles' %}">{% trans "Manage accounts" %}</a></li>
      {% endif %}
      <li><a {% if request.resolver_match.url_name == 'index' and 'contact' in request.resolver_match.app_names %}class="active"{% endif %} href="{% url 'contact:index' %}">{% trans "Contact us" %}</a></li>
    </ul>
  </div>
</nav>

portal/templates/includes/phase_banner.html
{% load i18n %}
<div class="phase-banner">
    <div>
        <strong class="tag tag--phase">ALPHA<span class="visually-hidden" >: </span></strong><span>{% trans 'This site will change as we test ideas.' %}</span>
    </div>
</div>